import { EventType, IEvent } from "@/types/types"

export const dummyEvents: IEvent[] = [
    {
        id: '1',
        title: 'React Conference',
        description: 'A conference about React and frontend development.',
        eventType: EventType.ONLINE,
        location: 'San Francisco',
        eventLink: 'https://reactconf.com',
        startDateTime: '2024-07-01T09:00:00.000Z',
        endDateTime: '2024-07-01T17:00:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'John Doe',
            email: 'john@example.com',
        },
    },
    {
        id: '2',
        title: 'Vue Meetup',
        description: 'Monthly Vue.js meetup.',
        eventType: EventType.IN_PERSON,
        location: 'New York',
        eventLink: 'https://vuemeetup.com',
        startDateTime: '2024-07-10T18:00:00.000Z',
        endDateTime: '2024-07-10T20:00:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Jane Smith',
            email: 'jane@example.com',
        },
    },
    {
        id: '3',
        title: 'Angular Workshop',
        description: 'Hands-on workshop for Angular beginners.',
        eventType: EventType.ONLINE,
        location: 'Online',
        eventLink: 'https://angularworkshop.com',
        startDateTime: '2024-07-15T13:00:00.000Z',
        endDateTime: '2024-07-15T16:00:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Alice Johnson',
            email: 'alice@example.com',
        },
    },
    {
        id: '4',
        title: 'Startup Pitch',
        description: 'Pitch your startup idea to investors.',
        eventType: EventType.ONLINE,
        location: 'Boston',
        eventLink: 'https://startuppitch.com',
        startDateTime: '2024-07-20T10:00:00.000Z',
        endDateTime: '2024-07-20T12:00:00.000Z',
        category: 'Business',
        organizer: {
            user_name: 'Bob Lee',
            email: 'bob@example.com',
        },
    },
    {
        id: '5',
        title: 'Design Sprint',
        description: 'A 5-day design sprint for product teams.',
        eventType: EventType.IN_PERSON,
        location: 'Remote',
        eventLink: 'https://designsprint.com',
        startDateTime: '2024-07-25T09:00:00.000Z',
        endDateTime: '2024-07-29T17:00:00.000Z',
        category: 'Design',
        organizer: {
            user_name: 'Carol King',
            email: 'carol@example.com',
        },
    },
    {
        id: '6',
        title: 'AI Bootcamp',
        description: 'Intensive bootcamp covering AI fundamentals.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://aibootcamp.com',
        startDateTime: '2024-08-02T08:30:00.000Z',
        endDateTime: '2024-08-02T16:00:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Eva Green',
            email: 'eva@example.com',
        },
    },
    {
        id: '7',
        title: 'Marketing Summit',
        description: 'Discuss modern marketing strategies and trends.',
        eventType: EventType.IN_PERSON,
        location: 'Los Angeles',
        eventLink: 'https://marketingsummit.com',
        startDateTime: '2024-08-05T10:00:00.000Z',
        endDateTime: '2024-08-05T15:00:00.000Z',
        category: 'Business',
        organizer: {
            user_name: 'Tom Hardy',
            email: 'tom@example.com',
        },
    },
    {
        id: '8',
        title: 'Figma UI Workshop',
        description: 'Learn advanced UI/UX design in Figma.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://figmaworkshop.com',
        startDateTime: '2024-08-10T11:00:00.000Z',
        endDateTime: '2024-08-10T13:30:00.000Z',
        category: 'Design',
        organizer: {
            user_name: 'Linda May',
            email: 'linda@example.com',
        },
    },
    {
        id: '9',
        title: 'Cybersecurity Essentials',
        description: 'Protect your systems and apps from common threats.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://cyberessentials.com',
        startDateTime: '2024-08-12T09:30:00.000Z',
        endDateTime: '2024-08-12T12:30:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Mark Hall',
            email: 'mark@example.com',
        },
    },
    {
        id: '10',
        title: 'Leadership Roundtable',
        description: 'Roundtable discussion for rising leaders.',
        eventType: EventType.IN_PERSON,
        location: 'Chicago',
        eventLink: 'https://leadershipround.com',
        startDateTime: '2024-08-14T14:00:00.000Z',
        endDateTime: '2024-08-14T17:00:00.000Z',
        category: 'Business',
        organizer: {
            user_name: 'Rachel Gray',
            email: 'rachel@example.com',
        },
    },
    {
        id: '11',
        title: 'Remote Work Trends 2025',
        description: 'Explore the future of remote and hybrid work.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://remotetrends.com',
        startDateTime: '2024-08-18T13:00:00.000Z',
        endDateTime: '2024-08-18T15:00:00.000Z',
        category: 'Business',
        organizer: {
            user_name: 'Nathan Fox',
            email: 'nathan@example.com',
        },
    },
    {
        id: '12',
        title: 'Next.js Masterclass',
        description: 'Master performance, routing, and SSR in Next.js.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://nextjsclass.com',
        startDateTime: '2024-08-20T10:00:00.000Z',
        endDateTime: '2024-08-20T13:00:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Diana Lee',
            email: 'diana@example.com',
        },
    },
    {
        id: '13',
        title: 'Agile Teams Workshop',
        description: 'Boost collaboration and velocity in Agile teams.',
        eventType: EventType.IN_PERSON,
        location: 'Seattle',
        eventLink: 'https://agileteams.com',
        startDateTime: '2024-08-22T09:00:00.000Z',
        endDateTime: '2024-08-22T16:00:00.000Z',
        category: 'Business',
        organizer: {
            user_name: 'George Kim',
            email: 'george@example.com',
        },
    },
    {
        id: '14',
        title: 'Creative Branding',
        description: 'How to build a brand people love.',
        eventType: EventType.ONLINE,
        location: 'Remote',
        eventLink: 'https://creativebrand.com',
        startDateTime: '2024-08-25T12:00:00.000Z',
        endDateTime: '2024-08-25T14:00:00.000Z',
        category: 'Design',
        organizer: {
            user_name: 'Nina Bell',
            email: 'nina@example.com',
        },
    },
    {
        id: '15',
        title: 'Docker & DevOps Meetup',
        description: 'Learn best practices for containers & CI/CD.',
        eventType: EventType.IN_PERSON,
        location: 'Austin',
        eventLink: 'https://dockmeetup.com',
        startDateTime: '2024-08-28T17:00:00.000Z',
        endDateTime: '2024-08-28T19:30:00.000Z',
        category: 'Tech',
        organizer: {
            user_name: 'Leo Pratt',
            email: 'leo@example.com',
        },
    },
];